version: "3.9"
services:
  api-gateway:
    build: "./api-gateway"
    depends_on:
      - api-server
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app

  api-server:
    build: "./api-server"
    ports:
      - 8000:8000
    volumes:
      - ./api-server:/opt/app

  api-server-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test123
    ports:
      - "27017:27017"
    volumes:
      - ./api-server-db:/opt/app
    command: mongod
